project:
  type: website
  output-dir: docs

website:
  favicon: images/MSlogo.png
  page-navigation: true
  title: "Max Scharf"
  description: "Personal Website for Max Scharf"
  site-url: "https://maxscharf.github.io/"
  
  
  navbar:
    background: "#000000"
    foreground: "#FFFFFF"
    style: docked
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Accomplishments"
        href: research.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: PDF_Files/Resume.pdf

    
    right: 
      - icon: github
        href: https://github.com/maxscharf
      - icon: envelope
        href: "mailto:maxjscharf@gmail.com"
        

            

format:
  html:
    max-width: 1600px
    theme: 
      dark: darkly
      light: cosmo
    css: style/styles.css
    toc: true
execute:
  freeze: auto




